backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images"
public_folder: "/images"
collections:
- label: "Cable Jointing Kits"
  name: "cables Jointing Kits"
  folder: "content/products/cable_jointing_kits"
  filter: {field: "type", value: "products"}
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Type, name: type, widget: "hidden", default: "products"}
    - label: Items
      name: items
      widget: list
      fields:
        - {label: Brand, name: brand, widget: string}
        - {label: Description, name: description, widget: text}
- label: "Cables And Wires"
  name: "cables and wires"
  folder: "content/products/cables_and_wires"
  filter: {field: "type", value: "products"}
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Type, name: type, widget: "hidden", default: "products"}
    - label: Items
      name: items
      widget: list
      fields:
        - {label: Brand, name: brand, widget: string}
        - {label: Description, name: description, widget: text}
- label: "Led Lighting"
  name: "led lighting"
  folder: "content/products/led_lighting"
  filter: {field: "type", value: "products"}
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Type, name: type, widget: "hidden", default: "products"}
    - label: Items
      name: items
      widget: list
      fields:
        - {label: Brand, name: brand, widget: string}
        - {label: Description, name: description, widget: text}
- label: "Lights And Light Fittings"
  name: "lights and light fittings"
  folder: "content/products/lights_and_light_fittings"
  filter: {field: "type", value: "products"}
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Type, name: type, widget: "hidden", default: "products"}
    - label: Items
      name: items
      widget: list
      fields:
        - {label: Brand, name: brand, widget: string}
        - {label: Description, name: description, widget: text}
- label: "Product Category"
  name: "product category"
  files:
    - label: "Cable Jointing Kits"
      name: "cables Jointing Kits"
      file: "content/products/cable_jointing_kits/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Type, name: type, widget: "hidden", default: "product_category"}
        - {label: Content, name: body, widget: markdown}
    - label: "Cables And Wires"
      name: "cables and wires"
      file: "content/products/cables_and_wires/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Type, name: type, widget: "hidden", default: "product_category"}
        - {label: Content, name: body, widget: markdown}
    - label: "Led Lighting"
      name: "led lighting"
      file: "content/products/led_lighting/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Type, name: type, widget: "hidden", default: "product_category"}
        - {label: Content, name: body, widget: markdown}
    - label: "Lights And Light Fittings"
      name: "lights and light fittings"
      file: "content/products/lights_and_light_fittings/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Type, name: type, widget: "hidden", default: "product_category"}
        - {label: Content, name: body, widget: markdown}
- label: "Pages"
  name: "pages"
  files:
    - label: "Home Page"
      name: "home"
      file: "content/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - label: Slides
          name: slides
          widget: list
          fields:
            - {label: Image, name: image, widget: image}
        - {label: Content, name: body, widget: markdown}
    - label: "Product"
      name: "product"
      file: "content/products/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Content, name: body, widget: markdown}
    - label: "About"
      name: "about"
      file: "content/about/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Content, name: body, widget: markdown}
    - label: "Contact Page"
      name: "contact"
      file: "content/contact/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Google Map Coordinates, name: google_map_coordinates, widget: string}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Business Name, name: business_name, widget: string}
        - {label: Business Location One, name: business_location_one, widget: string}
        - {label: Business Location Two, name: business_location_two, widget: string}
        - {label: Address One, name: address_one, widget: text}
        - {label: Phone No One, name: phone_one, widget: string}
        - {label: Fax One, name: Fax_one, widget: string}
        - {label: Email One, name: email_one, widget: string}
        - {label: Address Two, name: address_two, widget: text}
        - {label: Phone No Two, name: phone_two, widget: string}
        - {label: Fax Two, name: Fax_two, widget: string}
        - {label: Email Two, name: email_two, widget: string}
        - {label: Content, name: body, widget: markdown}
- label: "Data"
  name: "data"
  files:
    - label: "Brands"
      name: "brands"
      file: "data/brands.yml"
      fields:
        - label: Brands
          name: brands
          widget: list
          fields:
            - {label: Name, name: name, widget: string}
            - {label: Image, name: image, widget: image}
    - label: "Awards"
      name: "awards"
      file: "data/awards.yml"
      fields:
        - label: Awards
          name: awards
          widget: list
          fields:
            - {label: Image, name: image, widget: image}
    - label: "Meta"
      name: "meta"
      file: "data/meta.yml"
      fields:
        - {label: Page Background, name: background_image, widget: image}
        - {label: Logo, name: logo, widget: image}
        - {label: FB Cover, name: fb_cover, widget: image}
            
